name = "tp"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

kv_namespaces = [
	{ binding = "tp", id = "0a21e28f488d4bd982c06954186e2094", preview_id = "7e227473fd3a4f0e84224da800b24d99" },
]

[vars]
WORKERS_RS_VERSION = "0.0.16"

[build]
command = "cargo install -q worker-build && worker-build --release"
