name = "tp"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

kv_namespaces = [
	{ binding = "tp", id = "3b132b6bf45740c0bf32a90f69bbc548", preview_id = "8dd8c4057572466e95fab236667c25e8" },
]

[vars]
WORKERS_RS_VERSION = "0.0.16"

[build]
command = "cargo install -q worker-build && worker-build --release"
